
name: Build package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine64 wine32
    - run: npm install
    - run: npm run dist-win
    - run: npm run dist-linux
    - uses: actions/upload-artifact@v4
      with:
        name: linuxs
        path: dist/*.zip
