
name: Build package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: npm run dist-linux64
    - name: Upload .deb
      uses: actions/upload-artifact@v4
      with:
        name: electron-test_amd64.deb
        path: dist/*.deb
        compression: 0
    - name: Upload .tar.gz
      uses: actions/upload-artifact@v4
      with:
        name: electron-test_linux64.tar.gz
        path: dist/*.tar.gz
        compression: 0

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: npm run dist-win64
    - uses: actions/upload-artifact@v4
      with:
        name: electron-test_win64.zip
        path: dist/*-win.zip
        compression: 0
