
name: Build package

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run dist-linux64
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binaries
        path: |
          dist/electrontest-linux64.deb
          dist/electrontest-linux64.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        npm install
        npm run dist-win64
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: dist/electrontest-win64.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: binaries
        pattern: "*-binaries"
        merge-multiple: true
    - run: ls -R binaries
    - run: ls -R dist
    - name: Generate pre-release tag
      id: tag
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        TAG="v0.0.0-$(date +'%Y%m%d')-${SHORT_SHA}"
        echo "Generated tag: $TAG"
        echo "tag_name=$TAG" >> $GITHUB_OUTPUT
    - name: Create Alpha Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag_name }}
        name: Alpha Release ${{ steps.tag.outputs.tag_name }}
        prerelease: true
        generate_release_notes: true
        files: binaries/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
