
name: Build package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine64 wine32
    - run: npm install

    - run: npm run dist-win64
    - uses: actions/upload-artifact@v4
      with:
        name: electron-test-win64
        path: dist/*-win.zip

    - run: npm run dist-linux64
    - uses: actions/upload-artifact@v4
      with:
        name: electron-test-linux64-deb
        path: |
          dist/*.deb
    - uses: actions/upload-artifact@v4
      with:
        name: electron-test-linux64-targz
        path: |
          dist/*.tar.gz
